module Input

let input = [|
  {| Min = 9; Max = 10; Letter = 'm'; Code = "mmmmnxmmmwm" |}
  {| Min = 6; Max = 8; Letter = 'w'; Code = "wpwwhxnv" |}
  {| Min = 4; Max = 6; Letter = 'n'; Code = "trwpnnnvq" |}
  {| Min = 12; Max = 15; Letter = 'p'; Code = "zfpmpphpgghpppppppp" |}
  {| Min = 5; Max = 10; Letter = 'z'; Code = "bqlbzfzzzbzwsz" |}
  {| Min = 7; Max = 15; Letter = 'm'; Code = "mmkvmwmklnqpmggbgn" |}
  {| Min = 2; Max = 3; Letter = 'z'; Code = "zzzzzz" |}
  {| Min = 9; Max = 11; Letter = 'f'; Code = "fffffffffffff" |}
  {| Min = 8; Max = 10; Letter = 'l'; Code = "lllfllllll" |}
  {| Min = 1; Max = 3; Letter = 'l'; Code = "llll" |}
  {| Min = 2; Max = 9; Letter = 'm'; Code = "mjmmmmmmmm" |}
  {| Min = 3; Max = 4; Letter = 'm'; Code = "kmmm" |}
  {| Min = 2; Max = 11; Letter = 'f'; Code = "fjdfffmffffrff" |}
  {| Min = 14; Max = 16; Letter = 'm'; Code = "mmmmtmmmmmlmmmdmmm" |}
  {| Min = 1; Max = 5; Letter = 'k'; Code = "kmvkkkkkq" |}
  {| Min = 5; Max = 7; Letter = 'g'; Code = "mghggkgg" |}
  {| Min = 5; Max = 19; Letter = 't'; Code = "tdltgttttqmtjtjgxmp" |}
  {| Min = 5; Max = 7; Letter = 'r'; Code = "rrrrrrsrrrrrrrrrrr" |}
  {| Min = 15; Max = 16; Letter = 'q'; Code = "qqqqqqqqqqqqqqqqn" |}
  {| Min = 1; Max = 5; Letter = 'q'; Code = "qqtpqk" |}
  {| Min = 12; Max = 13; Letter = 't'; Code = "qzgpttrtlttjd" |}
  {| Min = 4; Max = 12; Letter = 'q'; Code = "jsvvqxtqhqqgntvvqqpq" |}
  {| Min = 13; Max = 17; Letter = 'f'; Code = "ffffffffffffrfffff" |}
  {| Min = 14; Max = 15; Letter = 'r'; Code = "rdxktqpprdrshdttg" |}
  {| Min = 8; Max = 10; Letter = 't'; Code = "ttpftttkppxttthhb" |}
  {| Min = 1; Max = 3; Letter = 'l'; Code = "hlwlpnc" |}
  {| Min = 16; Max = 17; Letter = 'n'; Code = "ntzqkmsnwtqjwtdnn" |}
  {| Min = 3; Max = 5; Letter = 'm'; Code = "jcmxmnpfwmxvmdd" |}
  {| Min = 16; Max = 19; Letter = 'c'; Code = "cmcccccckkccvcckzccc" |}
  {| Min = 6; Max = 9; Letter = 'g'; Code = "gcgggggfgln" |}
  {| Min = 5; Max = 9; Letter = 'r'; Code = "rrrkxrrrq" |}
  {| Min = 1; Max = 3; Letter = 't'; Code = "dxcsbvzrrtcfwrh" |}
  {| Min = 1; Max = 3; Letter = 'x'; Code = "xpxdbrhd" |}
  {| Min = 2; Max = 3; Letter = 'm'; Code = "mpfx" |}
  {| Min = 14; Max = 17; Letter = 'j'; Code = "fcjjpjjnmjptnjmjj" |}
  {| Min = 4; Max = 5; Letter = 'x'; Code = "xxxxr" |}
  {| Min = 10; Max = 13; Letter = 'n'; Code = "nnnpnnnnntntjn" |}
  {| Min = 11; Max = 12; Letter = 'j'; Code = "hzjkzgjjgjbvvjjhh" |}
  {| Min = 8; Max = 17; Letter = 'f'; Code = "ffhrvbzxfzffhzznfcj" |}
  {| Min = 1; Max = 5; Letter = 'p'; Code = "ppppppp" |}
  {| Min = 1; Max = 4; Letter = 'q'; Code = "vqqnqjqqwm" |}
  {| Min = 3; Max = 8; Letter = 'r'; Code = "rzrrrgtr" |}
  {| Min = 8; Max = 9; Letter = 'v'; Code = "vvtnxvdvs" |}
  {| Min = 16; Max = 17; Letter = 's'; Code = "dspssssssscsssssssss" |}
  {| Min = 10; Max = 13; Letter = 't'; Code = "tttttttttttttt" |}
  {| Min = 1; Max = 3; Letter = 's'; Code = "dslp" |}
  {| Min = 3; Max = 6; Letter = 'w'; Code = "wglwwxwwwwwww" |}
  {| Min = 1; Max = 6; Letter = 'p'; Code = "nppppc" |}
  {| Min = 6; Max = 10; Letter = 't'; Code = "tttztstttbnft" |}
  {| Min = 8; Max = 13; Letter = 'j'; Code = "cztwvjhjdmbbj" |}
  {| Min = 1; Max = 7; Letter = 'w'; Code = "wwnwzwwbbwwwswwwwtw" |}
  {| Min = 7; Max = 17; Letter = 'q'; Code = "qqqqqqbqqqqqqqqqq" |}
  {| Min = 4; Max = 11; Letter = 'v'; Code = "vvvvbvvvvvrcvwvvvvv" |}
  {| Min = 8; Max = 13; Letter = 'd'; Code = "dddddbhzdddddd" |}
  {| Min = 13; Max = 16; Letter = 'q'; Code = "qqqqqnqqqqqqcqqw" |}
  {| Min = 5; Max = 6; Letter = 'm'; Code = "mmmmnm" |}
  {| Min = 10; Max = 18; Letter = 'g'; Code = "jdpgfxfqlgtcckxsrgn" |}
  {| Min = 3; Max = 4; Letter = 'b'; Code = "bbgmb" |}
  {| Min = 12; Max = 14; Letter = 'l'; Code = "lkklrcllxlllllk" |}
  {| Min = 6; Max = 7; Letter = 'h'; Code = "kvxlzrvmd" |}
  {| Min = 3; Max = 4; Letter = 'b'; Code = "kbbg" |}
  {| Min = 3; Max = 5; Letter = 'v'; Code = "glgvs" |}
  {| Min = 3; Max = 6; Letter = 'x'; Code = "xxxxxxx" |}
  {| Min = 1; Max = 2; Letter = 'z'; Code = "zzfnb" |}
  {| Min = 5; Max = 6; Letter = 'b'; Code = "bqbbbx" |}
  {| Min = 3; Max = 5; Letter = 'j'; Code = "wjvsf" |}
  {| Min = 3; Max = 8; Letter = 'x'; Code = "fxxxkxxbxhxnx" |}
  {| Min = 11; Max = 12; Letter = 's'; Code = "vsssspcmqsbzsssss" |}
  {| Min = 3; Max = 4; Letter = 'v'; Code = "nvvvc" |}
  {| Min = 9; Max = 10; Letter = 'p'; Code = "pppppppppp" |}
  {| Min = 7; Max = 8; Letter = 'l'; Code = "pfclnccfn" |}
  {| Min = 14; Max = 17; Letter = 'c'; Code = "jcrjhgcccccnsccpc" |}
  {| Min = 3; Max = 4; Letter = 'p'; Code = "pjgcpxt" |}
  {| Min = 4; Max = 8; Letter = 'l'; Code = "wvlrptdftlpw" |}
  {| Min = 6; Max = 10; Letter = 'f'; Code = "hdnffrxfrf" |}
  {| Min = 2; Max = 5; Letter = 's'; Code = "ssssj" |}
  {| Min = 10; Max = 13; Letter = 'x'; Code = "xvlcrccxxxbxh" |}
  {| Min = 3; Max = 4; Letter = 'w'; Code = "wwwdw" |}
  {| Min = 9; Max = 15; Letter = 'g'; Code = "gggggggggggggggg" |}
  {| Min = 10; Max = 11; Letter = 'f'; Code = "flxvfffffwqk" |}
  {| Min = 5; Max = 6; Letter = 'l'; Code = "lllltvlll" |}
  {| Min = 8; Max = 9; Letter = 't'; Code = "vpdrntgdr" |}
  {| Min = 11; Max = 12; Letter = 'c'; Code = "bpxsnvhvfcprpwz" |}
  {| Min = 7; Max = 8; Letter = 'f'; Code = "wpgfvvzb" |}
  {| Min = 2; Max = 6; Letter = 'p'; Code = "dmccpk" |}
  {| Min = 7; Max = 11; Letter = 'd'; Code = "kwdblcxdrmr" |}
  {| Min = 3; Max = 4; Letter = 'g'; Code = "ggfzgggg" |}
  {| Min = 7; Max = 9; Letter = 'h'; Code = "hhhzcvdnz" |}
  {| Min = 4; Max = 8; Letter = 'l'; Code = "ttljxlxlw" |}
  {| Min = 12; Max = 15; Letter = 'x'; Code = "xtwwxxxcxxxxxxsx" |}
  {| Min = 10; Max = 13; Letter = 'd'; Code = "ddbhkdddddddd" |}
  {| Min = 1; Max = 4; Letter = 'j'; Code = "jjvtmc" |}
  {| Min = 8; Max = 11; Letter = 'b'; Code = "bbxcrjbmnnbmxfq" |}
  {| Min = 3; Max = 4; Letter = 'h'; Code = "hhhh" |}
  {| Min = 5; Max = 7; Letter = 'n'; Code = "nnnqwvgn" |}
  {| Min = 3; Max = 5; Letter = 'q'; Code = "qxlqvqq" |}
  {| Min = 4; Max = 9; Letter = 'k'; Code = "kkkkkkkkkkk" |}
  {| Min = 5; Max = 8; Letter = 'p'; Code = "spppxppwpppprppp" |}
  {| Min = 3; Max = 12; Letter = 'q'; Code = "qtkqqpqtqqqqqqqqqqq" |}
  {| Min = 16; Max = 17; Letter = 'x'; Code = "xzhxxxxxqnxmhxxpd" |}
  {| Min = 12; Max = 15; Letter = 'q'; Code = "rsrhzrghndsqslqnp" |}
  {| Min = 2; Max = 6; Letter = 'z'; Code = "rzzpzz" |}
  {| Min = 2; Max = 4; Letter = 'm'; Code = "mmbm" |}
  {| Min = 4; Max = 5; Letter = 'g'; Code = "gfgfq" |}
  {| Min = 1; Max = 6; Letter = 't'; Code = "stttsh" |}
  {| Min = 4; Max = 5; Letter = 'h'; Code = "hlhnm" |}
  {| Min = 12; Max = 13; Letter = 'd'; Code = "dddddddddddpd" |}
  {| Min = 9; Max = 10; Letter = 'h'; Code = "ghhhhhhhkchh" |}
  {| Min = 10; Max = 15; Letter = 'r'; Code = "rvgxrrcrrwrrrrtlrrr" |}
  {| Min = 5; Max = 10; Letter = 'l'; Code = "qltclnnblcrlv" |}
  {| Min = 11; Max = 17; Letter = 'p'; Code = "ppqpppvjbrpppqpppjw" |}
  {| Min = 9; Max = 12; Letter = 'g'; Code = "xghzsgmkggtg" |}
  {| Min = 13; Max = 15; Letter = 't'; Code = "jtdkhqttstxbztstt" |}
  {| Min = 14; Max = 18; Letter = 'c'; Code = "chcvxpcxccxckhcddh" |}
  {| Min = 12; Max = 14; Letter = 'd'; Code = "ddddddddsddddd" |}
  {| Min = 4; Max = 8; Letter = 'l'; Code = "rsdllblllxl" |}
  {| Min = 4; Max = 9; Letter = 'm'; Code = "xmrzbmrmhbsm" |}
  {| Min = 2; Max = 3; Letter = 's'; Code = "ptcp" |}
  {| Min = 5; Max = 8; Letter = 'p'; Code = "mtxhpvkpkrzhhjxpp" |}
  {| Min = 4; Max = 6; Letter = 'w'; Code = "wwwdwj" |}
  {| Min = 4; Max = 6; Letter = 'w'; Code = "wwwlwf" |}
  {| Min = 6; Max = 7; Letter = 'l'; Code = "zllntlr" |}
  {| Min = 10; Max = 14; Letter = 'd'; Code = "dqdddddddndddvddd" |}
  {| Min = 2; Max = 6; Letter = 'f'; Code = "dfpjwfgrfwlsc" |}
  {| Min = 3; Max = 5; Letter = 'n'; Code = "lnnxvq" |}
  {| Min = 4; Max = 19; Letter = 'b'; Code = "bbbbqbbbbbbjbbbsbbbb" |}
  {| Min = 4; Max = 12; Letter = 's'; Code = "mmlmthslfcnnrwkh" |}
  {| Min = 2; Max = 7; Letter = 'd'; Code = "ddddddd" |}
  {| Min = 3; Max = 7; Letter = 'j'; Code = "kpjwjjj" |}
  {| Min = 7; Max = 8; Letter = 'p'; Code = "pcmchppp" |}
  {| Min = 4; Max = 7; Letter = 'f'; Code = "fffvffgf" |}
  {| Min = 4; Max = 7; Letter = 'd'; Code = "ddmdfcv" |}
  {| Min = 13; Max = 14; Letter = 'w'; Code = "wjwmwwxwfmpdpf" |}
  {| Min = 5; Max = 7; Letter = 'd'; Code = "ddrdmsh" |}
  {| Min = 4; Max = 5; Letter = 'r'; Code = "rrrrrr" |}
  {| Min = 4; Max = 5; Letter = 'g'; Code = "ngsvg" |}
  {| Min = 7; Max = 13; Letter = 'g'; Code = "gggggggfggggggjg" |}
  {| Min = 6; Max = 10; Letter = 'm'; Code = "hbsqkpmfzss" |}
  {| Min = 8; Max = 10; Letter = 'p'; Code = "kppkdpptpmpnpl" |}
  {| Min = 3; Max = 4; Letter = 'l'; Code = "llll" |}
  {| Min = 11; Max = 12; Letter = 's'; Code = "ssssssssssqksq" |}
  {| Min = 15; Max = 16; Letter = 'd'; Code = "gdmdwdrzdkctddzv" |}
  {| Min = 7; Max = 13; Letter = 'd'; Code = "ddddddddqdddjd" |}
  {| Min = 7; Max = 8; Letter = 't'; Code = "tdtdrglm" |}
  {| Min = 3; Max = 6; Letter = 's'; Code = "sskssz" |}
  {| Min = 2; Max = 3; Letter = 'n'; Code = "nbnmrnxxfwqbdh" |}
  {| Min = 1; Max = 4; Letter = 'l'; Code = "wlxlllllllllllnpl" |}
  {| Min = 7; Max = 8; Letter = 'v'; Code = "khcxvvfd" |}
  {| Min = 14; Max = 15; Letter = 'j'; Code = "jjjjjjjjjjjjjbf" |}
  {| Min = 1; Max = 7; Letter = 'n'; Code = "ndncltg" |}
  {| Min = 1; Max = 5; Letter = 'l'; Code = "dllzmg" |}
  {| Min = 3; Max = 4; Letter = 'p'; Code = "zpzmp" |}
  {| Min = 1; Max = 6; Letter = 'b'; Code = "sbbbsb" |}
  {| Min = 11; Max = 13; Letter = 'x'; Code = "twcxxxxcxxxxd" |}
  {| Min = 3; Max = 4; Letter = 'r'; Code = "rrrtv" |}
  {| Min = 1; Max = 9; Letter = 'z'; Code = "kzvlzlnznzlhbdp" |}
  {| Min = 5; Max = 11; Letter = 'q'; Code = "qfbqbqnsjds" |}
  {| Min = 4; Max = 5; Letter = 'b'; Code = "wcjbb" |}
  {| Min = 2; Max = 4; Letter = 'b'; Code = "bdbn" |}
  {| Min = 3; Max = 12; Letter = 'g'; Code = "zftzmsbsjgggw" |}
  {| Min = 11; Max = 14; Letter = 'h'; Code = "hkhhhdhhhdfhhhh" |}
  {| Min = 1; Max = 2; Letter = 'z'; Code = "zzbz" |}
  {| Min = 6; Max = 15; Letter = 'z'; Code = "zznzzzzzzzzzzzzzzzzz" |}
  {| Min = 6; Max = 9; Letter = 'j'; Code = "jjjjjwjjm" |}
  {| Min = 2; Max = 3; Letter = 'h'; Code = "glghhh" |}
  {| Min = 16; Max = 17; Letter = 'r'; Code = "rhhdnrjrrbrgnrqjb" |}
  {| Min = 2; Max = 12; Letter = 'j'; Code = "jzjjchndjjbcfhmqkmn" |}
  {| Min = 1; Max = 4; Letter = 'n'; Code = "dnnn" |}
  {| Min = 7; Max = 12; Letter = 'w'; Code = "wswwwqmswqwcl" |}
  {| Min = 3; Max = 5; Letter = 'g'; Code = "ggvgz" |}
  {| Min = 1; Max = 3; Letter = 'c'; Code = "ccccmczccq" |}
  {| Min = 4; Max = 8; Letter = 'k'; Code = "rhckkkkksvkdkmkkvbrk" |}
  {| Min = 7; Max = 11; Letter = 'j'; Code = "gjwjhjjpsfqxnjd" |}
  {| Min = 3; Max = 4; Letter = 'n'; Code = "ndnjn" |}
  {| Min = 3; Max = 4; Letter = 'b'; Code = "gsbhb" |}
  {| Min = 4; Max = 5; Letter = 'z'; Code = "zzzzzz" |}
  {| Min = 2; Max = 12; Letter = 'f'; Code = "zltmcbkcvlsfjsm" |}
  {| Min = 8; Max = 11; Letter = 'g'; Code = "gggggggtxgmg" |}
  {| Min = 8; Max = 11; Letter = 'l'; Code = "lllllllllllll" |}
  {| Min = 1; Max = 18; Letter = 'd'; Code = "ddmlltqflhkpjdxrwdn" |}
  {| Min = 3; Max = 4; Letter = 'h'; Code = "hdhhh" |}
  {| Min = 3; Max = 11; Letter = 'w'; Code = "djwsxklbrbptcfcwcrch" |}
  {| Min = 7; Max = 9; Letter = 'm'; Code = "hshmlmmmmv" |}
  {| Min = 11; Max = 17; Letter = 'd'; Code = "dtcdddddhdjprmqdjb" |}
  {| Min = 3; Max = 6; Letter = 'c'; Code = "ccjccccv" |}
  {| Min = 12; Max = 16; Letter = 'r'; Code = "rrrrrrrrrrrrrrrrr" |}
  {| Min = 4; Max = 5; Letter = 'p'; Code = "hvpnc" |}
  {| Min = 2; Max = 11; Letter = 'z'; Code = "zzznvrzzvzzz" |}
  {| Min = 6; Max = 7; Letter = 's'; Code = "szfswss" |}
  {| Min = 19; Max = 20; Letter = 'p'; Code = "pppppppppppppppppppp" |}
  {| Min = 1; Max = 11; Letter = 'b'; Code = "bzkqmnbbwmkczz" |}
  {| Min = 15; Max = 17; Letter = 'd'; Code = "ddddddddddddddddd" |}
  {| Min = 5; Max = 12; Letter = 's'; Code = "xsskshskfvkrmsssv" |}
  {| Min = 2; Max = 17; Letter = 'r'; Code = "rrrrrrrrlrzrrwrrr" |}
  {| Min = 5; Max = 8; Letter = 'c'; Code = "cccclccn" |}
  {| Min = 7; Max = 11; Letter = 'k'; Code = "fnktjpzbcckjnqvmmnl" |}
  {| Min = 4; Max = 5; Letter = 'c'; Code = "cdzhcfvsc" |}
  {| Min = 2; Max = 8; Letter = 'f'; Code = "mfsfrfbs" |}
  {| Min = 11; Max = 12; Letter = 'r'; Code = "rqhjgnsrrrlj" |}
  {| Min = 5; Max = 7; Letter = 'r'; Code = "vbfjpzrr" |}
  {| Min = 2; Max = 4; Letter = 'd'; Code = "dwjl" |}
  {| Min = 5; Max = 9; Letter = 'f'; Code = "ddffrrfffffnfjr" |}
  {| Min = 1; Max = 12; Letter = 'h'; Code = "whghdlghthlxjmg" |}
  {| Min = 5; Max = 18; Letter = 'p'; Code = "lpppqplhsxpppppppqx" |}
  {| Min = 9; Max = 13; Letter = 'q'; Code = "xqkzksbsrgsqq" |}
  {| Min = 13; Max = 15; Letter = 'l'; Code = "llllllllllllllll" |}
  {| Min = 9; Max = 11; Letter = 'p'; Code = "whpfjshkxcjf" |}
  {| Min = 6; Max = 7; Letter = 'g'; Code = "gggggfbg" |}
  {| Min = 10; Max = 11; Letter = 'b'; Code = "bbbbbbtbbbb" |}
  {| Min = 2; Max = 4; Letter = 'n'; Code = "tnhn" |}
  {| Min = 12; Max = 13; Letter = 'q'; Code = "fqqqqqqqqqxfvvqq" |}
  {| Min = 6; Max = 7; Letter = 'd'; Code = "ctddrqw" |}
  {| Min = 6; Max = 8; Letter = 'n'; Code = "nzwnnzvnnnnrr" |}
  {| Min = 10; Max = 14; Letter = 'w'; Code = "qjlxjwdqzgthzs" |}
  {| Min = 6; Max = 14; Letter = 'n'; Code = "qnpznqnqdmnnnmcmqrbh" |}
  {| Min = 6; Max = 19; Letter = 'r'; Code = "lrrmrprlrbrpztrrrrr" |}
  {| Min = 3; Max = 7; Letter = 'p'; Code = "pwppghpp" |}
  {| Min = 6; Max = 12; Letter = 'l'; Code = "llllllllhllllllll" |}
  {| Min = 11; Max = 12; Letter = 'n'; Code = "nnznnnhnnnnn" |}
  {| Min = 17; Max = 19; Letter = 'b'; Code = "bbnbbbbbbbbbbbbbrbj" |}
  {| Min = 8; Max = 11; Letter = 'd'; Code = "dfddfdxdddd" |}
  {| Min = 4; Max = 5; Letter = 'w'; Code = "wwwxl" |}
  {| Min = 2; Max = 8; Letter = 'v'; Code = "xzvvvvvcvbvlz" |}
  {| Min = 6; Max = 7; Letter = 't'; Code = "ktttwct" |}
  {| Min = 2; Max = 4; Letter = 'l'; Code = "wltlc" |}
  {| Min = 5; Max = 12; Letter = 'd'; Code = "kqmpddtfzlfddsd" |}
  {| Min = 3; Max = 4; Letter = 'r'; Code = "rrrg" |}
  {| Min = 1; Max = 4; Letter = 'k'; Code = "dkks" |}
  {| Min = 3; Max = 6; Letter = 'v'; Code = "vvtvvh" |}
  {| Min = 14; Max = 15; Letter = 'c'; Code = "ccscchbcccccccc" |}
  {| Min = 2; Max = 8; Letter = 'v'; Code = "svvvhsvv" |}
  {| Min = 11; Max = 14; Letter = 'g'; Code = "gggggggggggggggp" |}
  {| Min = 8; Max = 10; Letter = 'v'; Code = "vvvvvvvvvvv" |}
  {| Min = 7; Max = 13; Letter = 'g'; Code = "gggggggggccggg" |}
  {| Min = 8; Max = 10; Letter = 'v'; Code = "vvvvvvpvvv" |}
  {| Min = 1; Max = 3; Letter = 'd'; Code = "dddd" |}
  {| Min = 5; Max = 6; Letter = 'w'; Code = "vrnpcw" |}
  {| Min = 9; Max = 12; Letter = 'w'; Code = "wwgwfwwwwgmw" |}
  {| Min = 7; Max = 11; Letter = 'w'; Code = "wwwwwwwwwwww" |}
  {| Min = 1; Max = 4; Letter = 'f'; Code = "fwft" |}
  {| Min = 6; Max = 8; Letter = 'n'; Code = "cnnbpnnnctnnvnldnj" |}
  {| Min = 8; Max = 17; Letter = 'r'; Code = "jrrmrrrfrrdrrjrsdr" |}
  {| Min = 5; Max = 7; Letter = 'r'; Code = "rrrrhrtr" |}
  {| Min = 5; Max = 6; Letter = 'z'; Code = "nxwtzzwlsmngkjzjgs" |}
  {| Min = 5; Max = 6; Letter = 'q'; Code = "qqqqqq" |}
  {| Min = 4; Max = 5; Letter = 'c'; Code = "sskrxc" |}
  {| Min = 3; Max = 9; Letter = 'f'; Code = "sjfstwfpffcdhfftbfvt" |}
  {| Min = 1; Max = 4; Letter = 'z'; Code = "zzzzzzzzzzzzzzzzzzz" |}
  {| Min = 5; Max = 6; Letter = 'f'; Code = "xmnfffb" |}
  {| Min = 1; Max = 3; Letter = 'z'; Code = "nzdzzz" |}
  {| Min = 8; Max = 13; Letter = 's'; Code = "sgsgbsssbsbsssk" |}
  {| Min = 5; Max = 7; Letter = 'v'; Code = "vlbqjhrmbvw" |}
  {| Min = 9; Max = 10; Letter = 'w'; Code = "wwwwwwwwgfwxwwwjwwww" |}
  {| Min = 5; Max = 7; Letter = 'n'; Code = "nkvqnnnn" |}
  {| Min = 3; Max = 14; Letter = 'b'; Code = "mzkkbbcbbmgxvbp" |}
  {| Min = 18; Max = 19; Letter = 'h'; Code = "hhhhhhhhhhhhwhhhhhh" |}
  {| Min = 3; Max = 6; Letter = 'g'; Code = "ggjvggggm" |}
  {| Min = 11; Max = 14; Letter = 'c'; Code = "ccccjclccccdcccncc" |}
  {| Min = 5; Max = 7; Letter = 'x'; Code = "xlckxxx" |}
  {| Min = 2; Max = 5; Letter = 'l'; Code = "lrlll" |}
  {| Min = 10; Max = 12; Letter = 't'; Code = "tttttdtttztjt" |}
  {| Min = 1; Max = 4; Letter = 'c'; Code = "cpkctsjp" |}
  {| Min = 6; Max = 11; Letter = 'c'; Code = "cccccccccccc" |}
  {| Min = 6; Max = 8; Letter = 'f'; Code = "cffvnrkfqmfffr" |}
  {| Min = 8; Max = 10; Letter = 'c'; Code = "cccmcccccc" |}
  {| Min = 2; Max = 4; Letter = 'm'; Code = "fdhdkxfmlz" |}
  {| Min = 5; Max = 7; Letter = 'g'; Code = "gggggjgggg" |}
  {| Min = 13; Max = 14; Letter = 'v'; Code = "vkhvpxdthvdvnrl" |}
  {| Min = 6; Max = 12; Letter = 'c'; Code = "cccgcrcchccqzsqsc" |}
  {| Min = 7; Max = 8; Letter = 'w'; Code = "wwwwwwcrwm" |}
  {| Min = 12; Max = 15; Letter = 's'; Code = "smmfsspsspsswss" |}
  {| Min = 7; Max = 14; Letter = 'p'; Code = "pxppsmppppppgqmpppp" |}
  {| Min = 6; Max = 13; Letter = 'z'; Code = "pjzzdzshcdgzcslr" |}
  {| Min = 8; Max = 10; Letter = 'q'; Code = "qqqqqqqqqqq" |}
  {| Min = 2; Max = 4; Letter = 'p'; Code = "ppppp" |}
  {| Min = 10; Max = 15; Letter = 't'; Code = "hqtttttqtltvttsttt" |}
  {| Min = 8; Max = 10; Letter = 'g'; Code = "qrvfmmggsr" |}
  {| Min = 6; Max = 7; Letter = 'd'; Code = "dddvdvdd" |}
  {| Min = 3; Max = 4; Letter = 'q'; Code = "qqkcq" |}
  {| Min = 1; Max = 2; Letter = 'l'; Code = "llgwzclzl" |}
  {| Min = 7; Max = 8; Letter = 'h'; Code = "hhhhhhgfhh" |}
  {| Min = 2; Max = 4; Letter = 'f'; Code = "fkcpq" |}
  {| Min = 3; Max = 5; Letter = 'r'; Code = "rrrrrrr" |}
  {| Min = 5; Max = 7; Letter = 'p'; Code = "pppppppkppwpk" |}
  {| Min = 4; Max = 5; Letter = 'j'; Code = "jgcjj" |}
  {| Min = 8; Max = 9; Letter = 'g'; Code = "gggggggggggvggg" |}
  {| Min = 7; Max = 10; Letter = 'p'; Code = "pplppptnpn" |}
  {| Min = 8; Max = 9; Letter = 'p'; Code = "pppppppwpp" |}
  {| Min = 4; Max = 5; Letter = 'k'; Code = "skkkk" |}
  {| Min = 11; Max = 17; Letter = 'f'; Code = "fkkffknfspfkxffvf" |}
  {| Min = 3; Max = 14; Letter = 'x'; Code = "xxmxxxxxxxxxxjxxx" |}
  {| Min = 2; Max = 4; Letter = 'r'; Code = "ndjpbrgjwsfpqlnrcr" |}
  {| Min = 8; Max = 10; Letter = 'w'; Code = "dgwzwwwdwtww" |}
  {| Min = 6; Max = 7; Letter = 'l'; Code = "mvdftllwnzxdwhcvl" |}
  {| Min = 9; Max = 11; Letter = 'v'; Code = "vvvvvvvvmvv" |}
  {| Min = 10; Max = 11; Letter = 'z'; Code = "pzzzlsfzppzzzzzlz" |}
  {| Min = 7; Max = 8; Letter = 'w'; Code = "wwwwwwww" |}
  {| Min = 3; Max = 5; Letter = 'r'; Code = "rrprrr" |}
  {| Min = 10; Max = 11; Letter = 'z'; Code = "zzzzzzzzzzzvz" |}
  {| Min = 7; Max = 8; Letter = 'q'; Code = "qqqqqqzmqz" |}
  {| Min = 9; Max = 10; Letter = 'g'; Code = "dggggggrqtgg" |}
  {| Min = 4; Max = 10; Letter = 'c'; Code = "cccfcccccz" |}
  {| Min = 5; Max = 12; Letter = 'g'; Code = "hfwkqmgxszhl" |}
  {| Min = 1; Max = 4; Letter = 'q'; Code = "dqqrqq" |}
  {| Min = 1; Max = 10; Letter = 'v'; Code = "qvvvvvvvgvvvv" |}
  {| Min = 6; Max = 7; Letter = 'l'; Code = "rhllzllll" |}
  {| Min = 2; Max = 4; Letter = 's'; Code = "sssssq" |}
  {| Min = 12; Max = 16; Letter = 'r'; Code = "rrrrrrrrrnrrrrrrrrrr" |}
  {| Min = 1; Max = 5; Letter = 'w'; Code = "wgwzc" |}
  {| Min = 12; Max = 13; Letter = 'l'; Code = "llhlldlmlllllll" |}
  {| Min = 4; Max = 8; Letter = 'b'; Code = "bbbbbbbkb" |}
  {| Min = 1; Max = 5; Letter = 'p'; Code = "ptpsp" |}
  {| Min = 4; Max = 6; Letter = 'd'; Code = "mjvdld" |}
  {| Min = 2; Max = 6; Letter = 'm'; Code = "mmvgtms" |}
  {| Min = 3; Max = 5; Letter = 'd'; Code = "rrdfdrddzw" |}
  {| Min = 1; Max = 5; Letter = 's'; Code = "ssssss" |}
  {| Min = 8; Max = 11; Letter = 'f'; Code = "qfflffffmffffffftx" |}
  {| Min = 2; Max = 10; Letter = 'x'; Code = "xxxxxrxxxxvxsxvxgxwx" |}
  {| Min = 3; Max = 5; Letter = 'v'; Code = "vkgqv" |}
  {| Min = 16; Max = 17; Letter = 'h'; Code = "hthhhhhhhhhhhhhrh" |}
  {| Min = 4; Max = 5; Letter = 'b'; Code = "bqplb" |}
  {| Min = 3; Max = 5; Letter = 'b'; Code = "txbbbqsbbksmbp" |}
  {| Min = 16; Max = 17; Letter = 'q'; Code = "nqjqqqqqqjdqqqqgl" |}
  {| Min = 4; Max = 5; Letter = 'x'; Code = "xlxcfxx" |}
  {| Min = 15; Max = 16; Letter = 'x'; Code = "xxxxxxxxxxxxxxmg" |}
  {| Min = 15; Max = 17; Letter = 't'; Code = "tkkttwttttttttttttt" |}
  {| Min = 6; Max = 7; Letter = 'v'; Code = "vvvfvvvvvvvvvvvvvvvv" |}
  {| Min = 9; Max = 13; Letter = 'j'; Code = "jjjjjjjzvjjjpj" |}
  {| Min = 6; Max = 11; Letter = 's'; Code = "sscsscswsfnsss" |}
  {| Min = 1; Max = 2; Letter = 'c'; Code = "cnpl" |}
  {| Min = 17; Max = 18; Letter = 'v'; Code = "vvvvvsvhvrvvvhvvqc" |}
  {| Min = 6; Max = 7; Letter = 'j'; Code = "jjbjjjjstjg" |}
  {| Min = 5; Max = 14; Letter = 'g'; Code = "gggmxgngggngggl" |}
  {| Min = 2; Max = 4; Letter = 'b'; Code = "bmbwbs" |}
  {| Min = 11; Max = 16; Letter = 'v'; Code = "cvrtvnvqvvcvvvvwv" |}
  {| Min = 16; Max = 19; Letter = 'c'; Code = "chccgvlclcnncdfcxcn" |}
  {| Min = 1; Max = 2; Letter = 'g'; Code = "rngb" |}
  {| Min = 5; Max = 7; Letter = 'j'; Code = "jjjdfjjjjj" |}
  {| Min = 5; Max = 6; Letter = 'g'; Code = "ggfghx" |}
  {| Min = 1; Max = 2; Letter = 'm'; Code = "pmgndcmg" |}
  {| Min = 10; Max = 12; Letter = 'w'; Code = "cwwwwjhznwcwswl" |}
  {| Min = 1; Max = 2; Letter = 'z'; Code = "zzzzzz" |}
  {| Min = 4; Max = 5; Letter = 'z'; Code = "hxmzh" |}
  {| Min = 1; Max = 2; Letter = 't'; Code = "thwxshrtldtvg" |}
  {| Min = 8; Max = 16; Letter = 'h'; Code = "hhhhhhhhhhhhhhhhhhh" |}
  {| Min = 6; Max = 18; Letter = 'q'; Code = "qqqqmqqqqbqxqqqqqqqq" |}
  {| Min = 4; Max = 5; Letter = 'g'; Code = "gjjgq" |}
  {| Min = 3; Max = 12; Letter = 'x'; Code = "txxxxvxjnxxxxxskhh" |}
  {| Min = 1; Max = 15; Letter = 'f'; Code = "fffnqfwrffhffff" |}
  {| Min = 7; Max = 10; Letter = 'g'; Code = "gpggzgggdkk" |}
  {| Min = 4; Max = 8; Letter = 'v'; Code = "vvvgbvvbzv" |}
  {| Min = 1; Max = 6; Letter = 'n'; Code = "cnqnnnb" |}
  {| Min = 1; Max = 3; Letter = 'k'; Code = "skzkkdk" |}
  {| Min = 10; Max = 11; Letter = 'z'; Code = "zzzzzzzqxhzt" |}
  {| Min = 7; Max = 16; Letter = 'p'; Code = "sppdxpdzppppdpvj" |}
  {| Min = 9; Max = 10; Letter = 'n'; Code = "nnnnnnnnfnnnnn" |}
  {| Min = 3; Max = 9; Letter = 'v'; Code = "vhvtkxzxvjp" |}
  {| Min = 7; Max = 15; Letter = 'h'; Code = "rtvchhhhhpdlzthz" |}
  {| Min = 5; Max = 10; Letter = 'd'; Code = "njqvdnrdddvptdf" |}
  {| Min = 1; Max = 5; Letter = 't'; Code = "ttgzttll" |}
  {| Min = 3; Max = 7; Letter = 'l'; Code = "zwzbwtdllsznz" |}
  {| Min = 5; Max = 8; Letter = 't'; Code = "btvtthtttd" |}
  {| Min = 6; Max = 7; Letter = 't'; Code = "tthtttb" |}
  {| Min = 3; Max = 17; Letter = 's'; Code = "zslvsbrlnqshsrgss" |}
  {| Min = 4; Max = 7; Letter = 'f'; Code = "fffffff" |}
  {| Min = 2; Max = 5; Letter = 'v'; Code = "vvvvgv" |}
  {| Min = 2; Max = 4; Letter = 'r'; Code = "crrr" |}
  {| Min = 8; Max = 9; Letter = 'k'; Code = "fklhhzskk" |}
  {| Min = 5; Max = 9; Letter = 'd'; Code = "dbddjdddkddddd" |}
  {| Min = 2; Max = 5; Letter = 'z'; Code = "svzkzbbkmj" |}
  {| Min = 2; Max = 4; Letter = 'f'; Code = "lgwf" |}
  {| Min = 2; Max = 4; Letter = 'q'; Code = "mvrzbd" |}
  {| Min = 6; Max = 13; Letter = 'r'; Code = "trrrrrrrdgrbrrrjrrx" |}
  {| Min = 16; Max = 17; Letter = 'g'; Code = "ggggggggggggggggg" |}
  {| Min = 6; Max = 15; Letter = 'p'; Code = "mhpcppnfnplhzjphs" |}
  {| Min = 5; Max = 10; Letter = 'l'; Code = "nvllkslllxlllzlj" |}
  {| Min = 3; Max = 8; Letter = 'l'; Code = "dclccbslwlslqlll" |}
  {| Min = 4; Max = 8; Letter = 'v'; Code = "vvvvvvvv" |}
  {| Min = 14; Max = 16; Letter = 'v'; Code = "svvvnvvxvvvqvvvn" |}
  {| Min = 8; Max = 13; Letter = 'z'; Code = "zzzzzrmzszfzpzzznzf" |}
  {| Min = 9; Max = 11; Letter = 'f'; Code = "ffffffffnfc" |}
  {| Min = 4; Max = 7; Letter = 'q'; Code = "qsxfqqc" |}
  {| Min = 2; Max = 6; Letter = 'h'; Code = "nhrnhhx" |}
  {| Min = 8; Max = 12; Letter = 'k'; Code = "mbkgxkvxqqkk" |}
  {| Min = 13; Max = 14; Letter = 'c'; Code = "lclkmkmcdxscww" |}
  {| Min = 4; Max = 5; Letter = 'p'; Code = "pppppp" |}
  {| Min = 2; Max = 4; Letter = 'l'; Code = "lbzmpv" |}
  {| Min = 3; Max = 4; Letter = 'g'; Code = "glggngprsgr" |}
  {| Min = 10; Max = 15; Letter = 'b'; Code = "bbbbbbbbbbbbbbbbbbb" |}
  {| Min = 11; Max = 17; Letter = 'z'; Code = "zzzzzzzzzzxzzzzzxz" |}
  {| Min = 7; Max = 8; Letter = 'q'; Code = "frvqpggq" |}
  {| Min = 9; Max = 10; Letter = 'f'; Code = "fffffkbffff" |}
  {| Min = 3; Max = 12; Letter = 'j'; Code = "jjjjjjjjjjjjjj" |}
  {| Min = 4; Max = 5; Letter = 'j'; Code = "jjbkd" |}
  {| Min = 1; Max = 2; Letter = 'm'; Code = "nmdmmmmmmm" |}
  {| Min = 14; Max = 16; Letter = 'w'; Code = "wwwwwwwwwwwwwwww" |}
  {| Min = 5; Max = 9; Letter = 'r'; Code = "rrkrrwhrrr" |}
  {| Min = 2; Max = 3; Letter = 'h'; Code = "hcfh" |}
  {| Min = 15; Max = 17; Letter = 'w'; Code = "zmwwwwwwgwwwwwwvwwww" |}
  {| Min = 8; Max = 13; Letter = 'r'; Code = "lzfczkplgdpqz" |}
  {| Min = 13; Max = 14; Letter = 'z'; Code = "qzzczzkgzzzmztcz" |}
  {| Min = 8; Max = 9; Letter = 'k'; Code = "kkstkcrkkmjbklk" |}
  {| Min = 12; Max = 13; Letter = 'w'; Code = "bkxwwwwwzwwwwwwwswx" |}
  {| Min = 7; Max = 8; Letter = 'x'; Code = "xxxxxxlvxx" |}
  {| Min = 2; Max = 4; Letter = 'l'; Code = "wlllsllll" |}
  {| Min = 5; Max = 6; Letter = 'c'; Code = "cmccccccv" |}
  {| Min = 3; Max = 4; Letter = 'p'; Code = "ppvs" |}
  {| Min = 5; Max = 12; Letter = 's'; Code = "fssssldsssxpvsx" |}
  {| Min = 5; Max = 12; Letter = 'g'; Code = "jvqrggdbglpgggkkxgg" |}
  {| Min = 7; Max = 8; Letter = 'g'; Code = "ggxgnjgggzbgjg" |}
  {| Min = 8; Max = 9; Letter = 'p'; Code = "pcppppppp" |}
  {| Min = 5; Max = 14; Letter = 'f'; Code = "bfffhffffhfsfff" |}
  {| Min = 2; Max = 5; Letter = 'f'; Code = "fffffff" |}
  {| Min = 3; Max = 12; Letter = 'x'; Code = "pxxxxxqkxhdqk" |}
  {| Min = 10; Max = 13; Letter = 'r'; Code = "rrrrrrrrrrrrrrrrrr" |}
  {| Min = 6; Max = 15; Letter = 'x'; Code = "nmxsfhbcvgvhxlx" |}
  {| Min = 5; Max = 9; Letter = 'v'; Code = "vvvvvvvvv" |}
  {| Min = 3; Max = 5; Letter = 's'; Code = "ssdsss" |}
  {| Min = 10; Max = 15; Letter = 'n'; Code = "cncwgtrhbnxpkwqzhvdn" |}
  {| Min = 10; Max = 13; Letter = 'j'; Code = "nfjjzvzjjqtpx" |}
  {| Min = 12; Max = 13; Letter = 'j'; Code = "jjjhjjjjjjjqr" |}
  {| Min = 9; Max = 12; Letter = 'h'; Code = "hhhhhhlhhhhhhh" |}
  {| Min = 9; Max = 11; Letter = 'l'; Code = "ljlllllfgvlll" |}
  {| Min = 1; Max = 4; Letter = 'p'; Code = "gbpp" |}
  {| Min = 6; Max = 7; Letter = 'x'; Code = "xtxxxhj" |}
  {| Min = 2; Max = 17; Letter = 'v'; Code = "vvvvvcvchvvtpvvvp" |}
  {| Min = 1; Max = 5; Letter = 'c'; Code = "bcccgc" |}
  {| Min = 2; Max = 5; Letter = 'p'; Code = "ppbxp" |}
  {| Min = 2; Max = 3; Letter = 'w'; Code = "wwwjwpjdjw" |}
  {| Min = 12; Max = 13; Letter = 'p'; Code = "pmcppzwpkppppppppd" |}
  {| Min = 17; Max = 18; Letter = 'w'; Code = "zgbwwwwzdwwswfxcgn" |}
  {| Min = 6; Max = 14; Letter = 'z'; Code = "wzlzbdzzzzmzqspbcn" |}
  {| Min = 9; Max = 15; Letter = 'q'; Code = "cttgqzglzxdqjhd" |}
  {| Min = 1; Max = 7; Letter = 'j'; Code = "rgjrjjjjj" |}
  {| Min = 6; Max = 9; Letter = 't'; Code = "tttttxtttttt" |}
  {| Min = 3; Max = 5; Letter = 'd'; Code = "rqkfq" |}
  {| Min = 3; Max = 12; Letter = 'c'; Code = "cckwqckkcxcmwvnkz" |}
  {| Min = 7; Max = 8; Letter = 'z'; Code = "zzkzdztgzz" |}
  {| Min = 3; Max = 5; Letter = 't'; Code = "wttttt" |}
  {| Min = 15; Max = 19; Letter = 'b'; Code = "bbbbbbbbbpbbbrbbbtb" |}
  {| Min = 10; Max = 11; Letter = 'p'; Code = "ppppppppprspphppp" |}
  {| Min = 5; Max = 7; Letter = 'v'; Code = "nvqvbrfbd" |}
  {| Min = 6; Max = 8; Letter = 'n'; Code = "vnnbhgnhn" |}
  {| Min = 7; Max = 11; Letter = 'r'; Code = "prfrrhshrszrssr" |}
  {| Min = 4; Max = 5; Letter = 'z'; Code = "qrszzht" |}
  {| Min = 7; Max = 9; Letter = 'z'; Code = "zzzzzczzzzzz" |}
  {| Min = 2; Max = 3; Letter = 'l'; Code = "lxtb" |}
  {| Min = 8; Max = 10; Letter = 'f'; Code = "ffffffrfff" |}
  {| Min = 10; Max = 11; Letter = 'q'; Code = "qqbgqqqcqqqq" |}
  {| Min = 2; Max = 9; Letter = 'l'; Code = "gmflclltxcllzm" |}
  {| Min = 8; Max = 13; Letter = 'k'; Code = "xkdglwzksvvdsjzp" |}
  {| Min = 7; Max = 8; Letter = 'h'; Code = "hjkbfhsc" |}
  {| Min = 13; Max = 14; Letter = 'x'; Code = "xxxxxxxxtxxxjbx" |}
  {| Min = 5; Max = 14; Letter = 'k'; Code = "kkgkkkkkkkkkkkkkk" |}
  {| Min = 11; Max = 13; Letter = 'g'; Code = "gwpggggggvxgzggg" |}
  {| Min = 4; Max = 6; Letter = 'j'; Code = "jjjjfj" |}
  {| Min = 2; Max = 3; Letter = 'b'; Code = "bxfb" |}
  {| Min = 1; Max = 2; Letter = 'k'; Code = "kkkp" |}
  {| Min = 9; Max = 17; Letter = 'g'; Code = "ggggggggkggggggghggg" |}
  {| Min = 3; Max = 4; Letter = 'p'; Code = "nzpb" |}
  {| Min = 5; Max = 6; Letter = 'f'; Code = "fbtfffv" |}
  {| Min = 4; Max = 10; Letter = 'h'; Code = "hhhrhhhhhhh" |}
  {| Min = 3; Max = 11; Letter = 'd'; Code = "wtddsbhwgfjmtlb" |}
  {| Min = 8; Max = 9; Letter = 'n'; Code = "nnnnnnqrm" |}
  {| Min = 9; Max = 14; Letter = 'c'; Code = "vchcclvtncscczbccw" |}
  {| Min = 7; Max = 9; Letter = 'q'; Code = "qqqqqnlqqqqq" |}
  {| Min = 12; Max = 13; Letter = 'k'; Code = "kkkkkckkkkkdh" |}
  {| Min = 4; Max = 9; Letter = 'v'; Code = "vvvvvvvnvvvv" |}
  {| Min = 2; Max = 5; Letter = 'z'; Code = "hhkzmwhzdfczf" |}
  {| Min = 4; Max = 5; Letter = 'q'; Code = "qqqqq" |}
  {| Min = 4; Max = 12; Letter = 'g'; Code = "gggggggggggggg" |}
  {| Min = 15; Max = 16; Letter = 's'; Code = "tnrtkspsszsmsmvs" |}
  {| Min = 13; Max = 16; Letter = 'h'; Code = "hhhhhhhhhhhhmhhjhhhh" |}
  {| Min = 7; Max = 9; Letter = 'f'; Code = "nhkmvtmfdcnfxflk" |}
  {| Min = 10; Max = 12; Letter = 't'; Code = "ttttttttsltw" |}
  {| Min = 1; Max = 5; Letter = 't'; Code = "nttttt" |}
  {| Min = 7; Max = 8; Letter = 'q'; Code = "qqqqntqbfqq" |}
  {| Min = 6; Max = 10; Letter = 'z'; Code = "zzzzzzzzzrz" |}
  {| Min = 10; Max = 17; Letter = 'k'; Code = "kkkkkrkkpkkkkxqvkkdk" |}
  {| Min = 2; Max = 6; Letter = 'w'; Code = "wqswjnwkx" |}
  {| Min = 9; Max = 18; Letter = 'l'; Code = "fvhwjrrvnfzqvvhdwkpj" |}
  {| Min = 2; Max = 5; Letter = 't'; Code = "rqpxmqmnswvbtp" |}
  {| Min = 15; Max = 19; Letter = 'l'; Code = "lfhlllllcbklgblllll" |}
  {| Min = 12; Max = 13; Letter = 'x'; Code = "lxzvxxxxxxxrcxxtxxx" |}
  {| Min = 4; Max = 5; Letter = 'n'; Code = "nngnb" |}
  {| Min = 5; Max = 14; Letter = 'j'; Code = "jjjjjjjjjjjjjx" |}
  {| Min = 3; Max = 4; Letter = 'q'; Code = "nqqqb" |}
  {| Min = 15; Max = 16; Letter = 'p'; Code = "ppvpppppppppdpfqp" |}
  {| Min = 2; Max = 10; Letter = 'k'; Code = "kkkkkkkkkkk" |}
  {| Min = 7; Max = 8; Letter = 'l'; Code = "mllllllc" |}
  {| Min = 19; Max = 20; Letter = 'w'; Code = "wwwwwwwwwwwwwwwwwhjb" |}
  {| Min = 2; Max = 4; Letter = 't'; Code = "rzmdfqjv" |}
  {| Min = 12; Max = 13; Letter = 'g'; Code = "gggkggggvgvgtgg" |}
  {| Min = 7; Max = 12; Letter = 'b'; Code = "qtjbzqbxbvsbwz" |}
  {| Min = 6; Max = 16; Letter = 'd'; Code = "wmpjjddmtctmxbqd" |}
  {| Min = 13; Max = 15; Letter = 'c'; Code = "fcznfkxzkftcfcfj" |}
  {| Min = 19; Max = 20; Letter = 'n'; Code = "nnnxnnnnnnnnnnnnnnnn" |}
  {| Min = 6; Max = 8; Letter = 'x'; Code = "gmgxxjxmxx" |}
  {| Min = 4; Max = 6; Letter = 'q'; Code = "qqqqqpqqqdqqqqqq" |}
  {| Min = 3; Max = 5; Letter = 'c'; Code = "cbcdc" |}
  {| Min = 6; Max = 7; Letter = 'k'; Code = "ktwkqrkfmkpkkt" |}
  {| Min = 9; Max = 12; Letter = 'p'; Code = "ppppppppqpwpp" |}
  {| Min = 16; Max = 20; Letter = 'c'; Code = "cccccccccccpfccdcbcl" |}
  {| Min = 6; Max = 9; Letter = 'q'; Code = "qqqqqzqqtfq" |}
  {| Min = 12; Max = 15; Letter = 'w'; Code = "wwpwwwvrwwwwwzs" |}
  {| Min = 9; Max = 10; Letter = 'd'; Code = "zddddhdfdd" |}
  {| Min = 11; Max = 12; Letter = 'c'; Code = "cclkzqccxbccglgc" |}
  {| Min = 6; Max = 11; Letter = 'v'; Code = "fzswbvbvddvpw" |}
  {| Min = 4; Max = 11; Letter = 'j'; Code = "vnkjmztfjvj" |}
  {| Min = 2; Max = 3; Letter = 'h'; Code = "jhhp" |}
  {| Min = 8; Max = 9; Letter = 'r'; Code = "rrrrrrrrr" |}
  {| Min = 1; Max = 10; Letter = 'd'; Code = "dddqdxdxdv" |}
  {| Min = 3; Max = 9; Letter = 'm'; Code = "cmmpvmmhmmx" |}
  {| Min = 6; Max = 7; Letter = 'm'; Code = "kpxtcmw" |}
  {| Min = 2; Max = 13; Letter = 's'; Code = "scjxbvrxfldhvf" |}
  {| Min = 3; Max = 11; Letter = 'w'; Code = "wftqlhxsqhkwxwscrgvp" |}
  {| Min = 2; Max = 3; Letter = 'r'; Code = "rrrq" |}
  {| Min = 1; Max = 2; Letter = 't'; Code = "tttd" |}
  {| Min = 6; Max = 7; Letter = 'b'; Code = "pbbbbbbbbb" |}
  {| Min = 2; Max = 6; Letter = 'p'; Code = "fkxlxnwpmxgtzv" |}
  {| Min = 12; Max = 14; Letter = 'w'; Code = "wwlwwclgwwwwwxwwm" |}
  {| Min = 4; Max = 5; Letter = 'q'; Code = "qqqkwq" |}
  {| Min = 11; Max = 16; Letter = 'q'; Code = "qqqqqqqxqdqqqqqn" |}
  {| Min = 2; Max = 3; Letter = 's'; Code = "sgmmkxgs" |}
  {| Min = 4; Max = 8; Letter = 'z'; Code = "zzzzzzzzzz" |}
  {| Min = 2; Max = 10; Letter = 'g'; Code = "srnlfvgfdwcjqdspwt" |}
  {| Min = 7; Max = 10; Letter = 'f'; Code = "fftfsblffj" |}
  {| Min = 5; Max = 8; Letter = 'b'; Code = "sbbmbbxb" |}
  {| Min = 4; Max = 8; Letter = 's'; Code = "hmpvsdsssvsczpw" |}
  {| Min = 1; Max = 4; Letter = 'h'; Code = "hghphn" |}
  {| Min = 3; Max = 7; Letter = 'r'; Code = "glmxmlnzsfvlr" |}
  {| Min = 6; Max = 8; Letter = 'n'; Code = "hncttfmt" |}
  {| Min = 3; Max = 5; Letter = 'w'; Code = "wwwww" |}
  {| Min = 12; Max = 14; Letter = 'f'; Code = "fhgfnffmmbfjlfq" |}
  {| Min = 9; Max = 10; Letter = 'q'; Code = "qqqqqqqqgq" |}
  {| Min = 6; Max = 7; Letter = 'k'; Code = "kkkkklkkkckkkkkfk" |}
  {| Min = 2; Max = 5; Letter = 's'; Code = "ssssss" |}
  {| Min = 3; Max = 8; Letter = 'd'; Code = "ddlddddsd" |}
  {| Min = 6; Max = 9; Letter = 'k'; Code = "kmkkvkkqkjfnkkkk" |}
  {| Min = 8; Max = 9; Letter = 'p'; Code = "qpslppfhx" |}
  {| Min = 14; Max = 15; Letter = 'j'; Code = "jjjjjjjjjjjjjch" |}
  {| Min = 2; Max = 5; Letter = 'z'; Code = "rbqmznmq" |}
  {| Min = 7; Max = 8; Letter = 'w'; Code = "wwwwwkwdwnq" |}
  {| Min = 4; Max = 7; Letter = 't'; Code = "cshbkttttt" |}
  {| Min = 1; Max = 2; Letter = 'f'; Code = "fqffvffffffffffh" |}
  {| Min = 4; Max = 5; Letter = 'p'; Code = "lfpbnvnbjsznxdpwp" |}
  {| Min = 1; Max = 2; Letter = 'w'; Code = "wwdczgfzhv" |}
  {| Min = 16; Max = 19; Letter = 'p'; Code = "ppppppppppsprpppppwp" |}
  {| Min = 2; Max = 11; Letter = 'f'; Code = "mfdlhdgflgz" |}
  {| Min = 5; Max = 6; Letter = 'h'; Code = "hhlhvj" |}
  {| Min = 2; Max = 6; Letter = 'n'; Code = "nntjzn" |}
  {| Min = 3; Max = 4; Letter = 'w'; Code = "wmwj" |}
  {| Min = 1; Max = 11; Letter = 'g'; Code = "gggghgggggggggggg" |}
  {| Min = 3; Max = 4; Letter = 'g'; Code = "jgjk" |}
  {| Min = 2; Max = 5; Letter = 's'; Code = "sjsss" |}
  {| Min = 2; Max = 3; Letter = 'h'; Code = "bkhk" |}
  {| Min = 2; Max = 13; Letter = 'h'; Code = "kbkbsjlvqxhfdwpstn" |}
  {| Min = 8; Max = 13; Letter = 'm'; Code = "mmmmmmmkmmmmmm" |}
  {| Min = 19; Max = 20; Letter = 's'; Code = "sssspsssssssssssssss" |}
  {| Min = 3; Max = 7; Letter = 'c'; Code = "jrrtcgx" |}
  {| Min = 15; Max = 18; Letter = 'm'; Code = "mmmmmmmmmmmmmmmggm" |}
  {| Min = 5; Max = 14; Letter = 'x'; Code = "ljxbxxxxxrnxxx" |}
  {| Min = 14; Max = 18; Letter = 'd'; Code = "pddddjddddkqdmdddcd" |}
  {| Min = 1; Max = 19; Letter = 'd'; Code = "tddpndddqdddddqgddd" |}
  {| Min = 7; Max = 14; Letter = 'b'; Code = "jfbbcbbpgdbvmb" |}
  {| Min = 1; Max = 7; Letter = 'h'; Code = "srvgwthwhhhh" |}
  {| Min = 1; Max = 4; Letter = 'n'; Code = "xhqdfnnng" |}
  {| Min = 1; Max = 2; Letter = 'v'; Code = "vbvvczs" |}
  {| Min = 10; Max = 14; Letter = 'g'; Code = "gggggpgggfgggg" |}
  {| Min = 11; Max = 14; Letter = 'd'; Code = "cnddvxddddnddldmf" |}
  {| Min = 2; Max = 3; Letter = 'd'; Code = "tddzccmml" |}
  {| Min = 2; Max = 4; Letter = 'x'; Code = "whfvct" |}
  {| Min = 2; Max = 5; Letter = 's'; Code = "cshcl" |}
  {| Min = 3; Max = 11; Letter = 'k'; Code = "ckgkkkxzkmzjl" |}
  {| Min = 10; Max = 11; Letter = 'm'; Code = "mmmmbmmmwkmm" |}
  {| Min = 11; Max = 12; Letter = 'g'; Code = "gjwgggnbgggggzggjg" |}
  {| Min = 2; Max = 16; Letter = 'j'; Code = "qkdlpxzmqkhxxxfskj" |}
  {| Min = 8; Max = 9; Letter = 'h'; Code = "hkhxhhkqt" |}
  {| Min = 6; Max = 7; Letter = 'w'; Code = "wwdswwwwwcqlw" |}
  {| Min = 2; Max = 9; Letter = 'w'; Code = "bwsgvbwjrv" |}
  {| Min = 17; Max = 20; Letter = 't'; Code = "hknjzjzdwsqkbktkqfts" |}
  {| Min = 1; Max = 3; Letter = 'c'; Code = "cjcsqfpgjppcccn" |}
  {| Min = 8; Max = 9; Letter = 'n'; Code = "mnnnnznzngnnt" |}
  {| Min = 6; Max = 8; Letter = 'k'; Code = "lgckxwkk" |}
  {| Min = 3; Max = 6; Letter = 'l'; Code = "lsnldll" |}
  {| Min = 8; Max = 13; Letter = 's'; Code = "svsscsfcdsxvlksxtk" |}
  {| Min = 5; Max = 6; Letter = 't'; Code = "xttzsvtt" |}
  {| Min = 9; Max = 13; Letter = 't'; Code = "ttttstttvjbtr" |}
  {| Min = 3; Max = 4; Letter = 's'; Code = "sqxss" |}
  {| Min = 6; Max = 14; Letter = 's'; Code = "ssscsssssdssssssts" |}
  {| Min = 2; Max = 15; Letter = 't'; Code = "ztddqtbtttlfhttttpt" |}
  {| Min = 6; Max = 8; Letter = 'b'; Code = "btbbbvbm" |}
  {| Min = 6; Max = 8; Letter = 'l'; Code = "llllllllsllll" |}
  {| Min = 1; Max = 4; Letter = 'l'; Code = "zlcv" |}
  {| Min = 10; Max = 15; Letter = 'f'; Code = "bfstdfjfffmffffffgc" |}
  {| Min = 4; Max = 8; Letter = 'z'; Code = "zzzbzzzvzz" |}
  {| Min = 5; Max = 7; Letter = 'h'; Code = "qhmxhkhsjmwzkvh" |}
  {| Min = 8; Max = 12; Letter = 'f'; Code = "lfffqffxfrfd" |}
  {| Min = 5; Max = 14; Letter = 'c'; Code = "kcjbzhcfmrvrxkpnjd" |}
  {| Min = 5; Max = 7; Letter = 'b'; Code = "bbbblbb" |}
  {| Min = 3; Max = 5; Letter = 't'; Code = "tgthtt" |}
  {| Min = 5; Max = 6; Letter = 's'; Code = "ssxssspsc" |}
  {| Min = 4; Max = 5; Letter = 'z'; Code = "wzhzz" |}
  {| Min = 1; Max = 5; Letter = 'b'; Code = "bbbbbb" |}
  {| Min = 4; Max = 11; Letter = 'j'; Code = "sjtbrnspzndg" |}
  {| Min = 1; Max = 8; Letter = 'g'; Code = "lbscqdrdtqgmtsg" |}
  {| Min = 4; Max = 15; Letter = 'c'; Code = "cdccnpccscclcccccc" |}
  {| Min = 4; Max = 5; Letter = 's'; Code = "smsssz" |}
  {| Min = 6; Max = 9; Letter = 'b'; Code = "bbbbbtbbqbk" |}
  {| Min = 10; Max = 13; Letter = 'h'; Code = "hhfkhhfhhmhgq" |}
  {| Min = 3; Max = 4; Letter = 's'; Code = "hhsg" |}
  {| Min = 12; Max = 14; Letter = 's'; Code = "ssssssssssssssdss" |}
  {| Min = 5; Max = 6; Letter = 'w'; Code = "qfxnvk" |}
  {| Min = 4; Max = 8; Letter = 'v'; Code = "fvvvvvvvjs" |}
  {| Min = 5; Max = 11; Letter = 'f'; Code = "ffffffffffnff" |}
  {| Min = 7; Max = 16; Letter = 'd'; Code = "knfdxddwdddnwdjdddl" |}
  {| Min = 12; Max = 13; Letter = 'd'; Code = "dddddddddddrw" |}
  {| Min = 16; Max = 17; Letter = 'w'; Code = "wsxwwwwwwwwwwwwltw" |}
  {| Min = 6; Max = 10; Letter = 'w'; Code = "wtwjcsjwhgw" |}
  {| Min = 2; Max = 7; Letter = 'v'; Code = "spvscsxhjfjfdff" |}
  {| Min = 11; Max = 14; Letter = 'k'; Code = "scpskhmkwkqhzm" |}
  {| Min = 16; Max = 17; Letter = 'm'; Code = "mqmmmmmfmmzmbmmwg" |}
  {| Min = 11; Max = 12; Letter = 'p'; Code = "pppkppppqwpc" |}
  {| Min = 2; Max = 11; Letter = 'd'; Code = "ddgssqrdqqdd" |}
  {| Min = 5; Max = 18; Letter = 'z'; Code = "wrghzskqlgxqmqczsxvf" |}
  {| Min = 13; Max = 14; Letter = 't'; Code = "tzttttvftrttttkj" |}
  {| Min = 12; Max = 16; Letter = 'w'; Code = "hxvdgjwsbclrmrtwxc" |}
  {| Min = 1; Max = 11; Letter = 'x'; Code = "bnxdfxgfxfq" |}
  {| Min = 9; Max = 10; Letter = 'k'; Code = "mwsnrdbcqrvxlk" |}
  {| Min = 1; Max = 8; Letter = 'j'; Code = "qprjjjzlj" |}
  {| Min = 17; Max = 18; Letter = 'f'; Code = "fjfffncffffwfdxfgvfd" |}
  {| Min = 4; Max = 5; Letter = 'j'; Code = "pjjjc" |}
  {| Min = 1; Max = 2; Letter = 'j'; Code = "jjjh" |}
  {| Min = 2; Max = 4; Letter = 'v'; Code = "tvpv" |}
  {| Min = 8; Max = 12; Letter = 'x'; Code = "fxxxxxxbxxxhx" |}
  {| Min = 9; Max = 10; Letter = 'f'; Code = "xfffffffffffffffjnf" |}
  {| Min = 1; Max = 5; Letter = 'k'; Code = "vkkknk" |}
  {| Min = 3; Max = 4; Letter = 's'; Code = "qtsrfsvsvsrtc" |}
  {| Min = 5; Max = 6; Letter = 'z'; Code = "zzmzkj" |}
  {| Min = 1; Max = 12; Letter = 'n'; Code = "snnnnnnnnnnnnnnnn" |}
  {| Min = 2; Max = 5; Letter = 'm'; Code = "mjmml" |}
  {| Min = 9; Max = 11; Letter = 'n'; Code = "nnnnnnlnnngnnnv" |}
  {| Min = 2; Max = 3; Letter = 'x'; Code = "fxxxxckxsrlwhc" |}
  {| Min = 5; Max = 15; Letter = 'd'; Code = "rdpjlddjdrddxbddt" |}
  {| Min = 5; Max = 17; Letter = 'c'; Code = "bccbbckwvcrmdcqcctcc" |}
  {| Min = 6; Max = 8; Letter = 'w'; Code = "wwjwwswrwpnwgxnd" |}
  {| Min = 7; Max = 10; Letter = 'p'; Code = "pppppppppppppp" |}
  {| Min = 3; Max = 18; Letter = 'h'; Code = "hhlhhjnwhhbhhzhhhthj" |}
  {| Min = 2; Max = 7; Letter = 'b'; Code = "llbbcrjbnb" |}
  {| Min = 1; Max = 6; Letter = 's'; Code = "ssbssfkss" |}
  {| Min = 2; Max = 3; Letter = 'm'; Code = "zhnmd" |}
  {| Min = 10; Max = 12; Letter = 't'; Code = "ttlttzttllbjtttttt" |}
  {| Min = 8; Max = 10; Letter = 'w'; Code = "wwbwwwwwmw" |}
  {| Min = 4; Max = 5; Letter = 'r'; Code = "rrrfh" |}
  {| Min = 1; Max = 4; Letter = 'l'; Code = "lfblrlpzzlqljlsll" |}
  {| Min = 3; Max = 4; Letter = 'c'; Code = "cwcjmh" |}
  {| Min = 14; Max = 16; Letter = 'h'; Code = "hhhhjhhhhxhhhlhkxhh" |}
  {| Min = 7; Max = 8; Letter = 'm'; Code = "mmvcmqmdmkbmmmn" |}
  {| Min = 5; Max = 7; Letter = 'm'; Code = "dwmqmmmkmkm" |}
  {| Min = 1; Max = 4; Letter = 'd'; Code = "ddddm" |}
  {| Min = 12; Max = 16; Letter = 'd'; Code = "dqlpddwndmrdvdmdghdh" |}
  {| Min = 18; Max = 20; Letter = 'v'; Code = "gzqvmvzvcffwbfnvhmnq" |}
  {| Min = 4; Max = 5; Letter = 'c'; Code = "cckcc" |}
  {| Min = 9; Max = 14; Letter = 'x'; Code = "xxxxthxxgjbxxrx" |}
  {| Min = 6; Max = 12; Letter = 'z'; Code = "vkxzzjzzzjfp" |}
  {| Min = 11; Max = 14; Letter = 'h'; Code = "hczhgqsbsmtrhf" |}
  {| Min = 6; Max = 8; Letter = 'x'; Code = "kjvscxnxfvxbmgnksxq" |}
  {| Min = 7; Max = 9; Letter = 'k'; Code = "kvffnskdkdq" |}
  {| Min = 6; Max = 7; Letter = 'x'; Code = "xxxxcxx" |}
  {| Min = 6; Max = 12; Letter = 'm'; Code = "mrmmmcmjzmftgmmtm" |}
  {| Min = 13; Max = 17; Letter = 'f'; Code = "ffqfffffpffqmfnhgbf" |}
  {| Min = 8; Max = 10; Letter = 'r'; Code = "rrmjrktmjbrrrrsl" |}
  {| Min = 8; Max = 13; Letter = 'c'; Code = "cccccnnrccccvqcnclcc" |}
  {| Min = 1; Max = 4; Letter = 't'; Code = "tttg" |}
  {| Min = 13; Max = 17; Letter = 'j'; Code = "jpjjjjjjjjjjtjjjtjz" |}
  {| Min = 3; Max = 5; Letter = 'r'; Code = "rrlrl" |}
  {| Min = 3; Max = 18; Letter = 'c'; Code = "cjshpccrvfxggcfjsfwq" |}
  {| Min = 2; Max = 7; Letter = 'l'; Code = "ldlrxqqbqllgj" |}
  {| Min = 1; Max = 3; Letter = 'v'; Code = "bvxr" |}
  {| Min = 5; Max = 6; Letter = 't'; Code = "tttttt" |}
  {| Min = 17; Max = 19; Letter = 'b'; Code = "pqbmnhbksnqqxbhlxjcr" |}
  {| Min = 4; Max = 5; Letter = 'p'; Code = "ppppp" |}
  {| Min = 1; Max = 4; Letter = 'm'; Code = "mmmmmm" |}
  {| Min = 1; Max = 9; Letter = 'b'; Code = "vbtbbbbbbfbbqb" |}
  {| Min = 6; Max = 10; Letter = 'j'; Code = "fzqldjzgdjrjt" |}
  {| Min = 6; Max = 7; Letter = 'w'; Code = "wwwwwwzwwvww" |}
  {| Min = 8; Max = 9; Letter = 'r'; Code = "rrrrrrrrrr" |}
  {| Min = 5; Max = 8; Letter = 'h'; Code = "xhvjhhlhdwvh" |}
  {| Min = 7; Max = 10; Letter = 'w'; Code = "wwwwgwlwwgwwww" |}
  {| Min = 5; Max = 9; Letter = 'f'; Code = "lvvfcfqffv" |}
  {| Min = 4; Max = 6; Letter = 'n'; Code = "nnnnnr" |}
  {| Min = 2; Max = 3; Letter = 'c'; Code = "wdbq" |}
  {| Min = 19; Max = 20; Letter = 'l'; Code = "lglllllllllllllvllrl" |}
  {| Min = 5; Max = 9; Letter = 'z'; Code = "zzddzzzwz" |}
  {| Min = 3; Max = 4; Letter = 'd'; Code = "dkddvdd" |}
  {| Min = 10; Max = 14; Letter = 'f'; Code = "fmffffffrsfnfx" |}
  {| Min = 4; Max = 5; Letter = 'p'; Code = "pvpwvqplmprp" |}
  {| Min = 4; Max = 10; Letter = 'c'; Code = "ctclccccvbcccc" |}
  {| Min = 5; Max = 6; Letter = 'h'; Code = "hhhzhh" |}
  {| Min = 7; Max = 14; Letter = 'g'; Code = "ggggggggkgggggggwgg" |}
  {| Min = 8; Max = 11; Letter = 'b'; Code = "bbrbbxbgbbb" |}
  {| Min = 3; Max = 4; Letter = 'q'; Code = "qpxq" |}
  {| Min = 2; Max = 4; Letter = 'z'; Code = "xkrv" |}
  {| Min = 2; Max = 3; Letter = 'm'; Code = "mmmm" |}
  {| Min = 9; Max = 10; Letter = 'w'; Code = "wwwwzwlzwcwwbpfrrf" |}
  {| Min = 7; Max = 12; Letter = 't'; Code = "kthhmbddtbhs" |}
  {| Min = 2; Max = 4; Letter = 't'; Code = "tttjtt" |}
  {| Min = 5; Max = 7; Letter = 'w'; Code = "xvwwwwww" |}
  {| Min = 10; Max = 12; Letter = 'g'; Code = "gdmgghnkmgggmwjrlgjj" |}
  {| Min = 4; Max = 6; Letter = 'j'; Code = "jzknjjt" |}
  {| Min = 1; Max = 10; Letter = 'v'; Code = "vvvvvvvvvc" |}
  {| Min = 8; Max = 11; Letter = 'w'; Code = "znmpmrffmswnqw" |}
  {| Min = 7; Max = 12; Letter = 'w'; Code = "dxpvfwcgwwwwwxwww" |}
  {| Min = 3; Max = 4; Letter = 'z'; Code = "zbzzt" |}
  {| Min = 4; Max = 18; Letter = 'r'; Code = "frqhkrqbcttrdqkgnr" |}
  {| Min = 9; Max = 12; Letter = 's'; Code = "dssxrzjsfssv" |}
  {| Min = 2; Max = 4; Letter = 'w'; Code = "fwjw" |}
  {| Min = 11; Max = 13; Letter = 'r'; Code = "kdrrrrrrvrrrqrprr" |}
  {| Min = 7; Max = 10; Letter = 'g'; Code = "gggggggggg" |}
  {| Min = 1; Max = 5; Letter = 'v'; Code = "vdvvv" |}
  {| Min = 19; Max = 20; Letter = 's'; Code = "vmswvsbspsgsvszssbss" |}
  {| Min = 4; Max = 5; Letter = 'q'; Code = "qqqqqq" |}
  {| Min = 6; Max = 9; Letter = 'l'; Code = "llrdllwlwlll" |}
  {| Min = 9; Max = 11; Letter = 'm'; Code = "mmmdmmmmkmhgmkmmmm" |}
  {| Min = 1; Max = 3; Letter = 'g'; Code = "sgfg" |}
  {| Min = 12; Max = 14; Letter = 'g'; Code = "gggggggggrggpgggrb" |}
  {| Min = 6; Max = 9; Letter = 'x'; Code = "zdzplkrxxkkrjpxnsdzl" |}
  {| Min = 14; Max = 19; Letter = 'h'; Code = "htclqdvhdzqhxbhzhkh" |}
  {| Min = 2; Max = 4; Letter = 'm'; Code = "wmmmt" |}
  {| Min = 3; Max = 4; Letter = 'p'; Code = "sjpp" |}
  {| Min = 3; Max = 4; Letter = 'h'; Code = "hhrx" |}
  {| Min = 2; Max = 3; Letter = 'r'; Code = "zhlzpzc" |}
  {| Min = 14; Max = 20; Letter = 'j'; Code = "nffzpjmqrjbjjfjjmcjl" |}
  {| Min = 4; Max = 6; Letter = 'w'; Code = "wmpjwzzd" |}
  {| Min = 7; Max = 8; Letter = 'q'; Code = "qqqqqqqq" |}
  {| Min = 4; Max = 5; Letter = 'n'; Code = "rgcvfnbn" |}
  {| Min = 3; Max = 4; Letter = 'g'; Code = "qgmcgs" |}
  {| Min = 4; Max = 8; Letter = 'v'; Code = "vvzlzxhclv" |}
  {| Min = 7; Max = 8; Letter = 'g'; Code = "szsgfzgqjnj" |}
  {| Min = 12; Max = 15; Letter = 'w'; Code = "wwwwwwwwwwwwkwd" |}
  {| Min = 11; Max = 12; Letter = 't'; Code = "ttttjtttttpz" |}
  {| Min = 5; Max = 6; Letter = 'q'; Code = "gdmrqq" |}
  {| Min = 5; Max = 7; Letter = 'w'; Code = "nwwwwwrw" |}
  {| Min = 1; Max = 4; Letter = 's'; Code = "srpm" |}
  {| Min = 14; Max = 18; Letter = 'w'; Code = "wwwwwfwwwwwwwnwwwrw" |}
  {| Min = 7; Max = 9; Letter = 'z'; Code = "zzzsznjzrfzw" |}
  {| Min = 3; Max = 18; Letter = 'v'; Code = "vvxvvvkvvvbvvgjvvvv" |}
  {| Min = 2; Max = 16; Letter = 'p'; Code = "mmnsdmhhkfqplzcwq" |}
  {| Min = 1; Max = 2; Letter = 'h'; Code = "hhlmvhw" |}
  {| Min = 7; Max = 8; Letter = 'n'; Code = "nnnznqnn" |}
  {| Min = 3; Max = 4; Letter = 'n'; Code = "hnnn" |}
  {| Min = 5; Max = 6; Letter = 'p'; Code = "zvbdhnpkcpggvlxppp" |}
  {| Min = 3; Max = 4; Letter = 'l'; Code = "lljgll" |}
  {| Min = 1; Max = 5; Letter = 'd'; Code = "ndddmddddd" |}
  {| Min = 3; Max = 4; Letter = 't'; Code = "dttt" |}
  {| Min = 4; Max = 5; Letter = 'm'; Code = "wmmzm" |}
  {| Min = 6; Max = 8; Letter = 'm'; Code = "mhmmmvmwm" |}
  {| Min = 8; Max = 11; Letter = 'b'; Code = "wxzvmmvbxqbjb" |}
  {| Min = 18; Max = 19; Letter = 'x'; Code = "xdtszmmqxlxzvxgxwvj" |}
  {| Min = 15; Max = 19; Letter = 'r'; Code = "rrrrrrrpwfrrrrrrrrrr" |}
  {| Min = 9; Max = 17; Letter = 'j'; Code = "jjjjjjrjjjjjjvjjjjqj" |}
  {| Min = 2; Max = 5; Letter = 't'; Code = "nmxwtthqstg" |}
  {| Min = 9; Max = 17; Letter = 'h'; Code = "chjkngjkkrnkhgtgv" |}
  {| Min = 2; Max = 4; Letter = 'r'; Code = "rrrr" |}
  {| Min = 10; Max = 16; Letter = 'l'; Code = "lpdlllmsllfkllll" |}
  {| Min = 2; Max = 4; Letter = 'g'; Code = "gxgmg" |}
  {| Min = 4; Max = 5; Letter = 'h'; Code = "rnhhh" |}
  {| Min = 2; Max = 5; Letter = 'j'; Code = "jqnvqlntsccr" |}
  {| Min = 2; Max = 6; Letter = 'x'; Code = "dxdxwxfxfnxx" |}
  {| Min = 5; Max = 19; Letter = 's'; Code = "fsnpsdhkbqnscbdjphf" |}
  {| Min = 5; Max = 10; Letter = 'v'; Code = "hclvbnmvwvvcvsgxbdcv" |}
  {| Min = 2; Max = 10; Letter = 'r'; Code = "gfczjcpjbdlf" |}
  {| Min = 4; Max = 9; Letter = 'm'; Code = "mmmxmmmmmm" |}
  {| Min = 4; Max = 14; Letter = 'b'; Code = "bpjgdxbbbvbgbbbb" |}
  {| Min = 6; Max = 8; Letter = 'w'; Code = "qhwwbwwww" |}
  {| Min = 7; Max = 10; Letter = 'x'; Code = "wjxzxxxfxxs" |}
  {| Min = 7; Max = 9; Letter = 'w'; Code = "hwjdwfjgqcwhlwwwwg" |}
  {| Min = 3; Max = 8; Letter = 'v'; Code = "vbvwpnmv" |}
  {| Min = 1; Max = 9; Letter = 'h'; Code = "chhhhhhdnh" |}
  {| Min = 3; Max = 4; Letter = 'l'; Code = "qgllflwhsbq" |}
  {| Min = 6; Max = 9; Letter = 'q'; Code = "qzqkqqzqqlfmfq" |}
  {| Min = 3; Max = 12; Letter = 'm'; Code = "mmwmvmmmmdmmzlbtmr" |}
  {| Min = 3; Max = 5; Letter = 'n'; Code = "nnknwn" |}
  {| Min = 7; Max = 8; Letter = 'b'; Code = "bbnbbbxs" |}
  {| Min = 2; Max = 4; Letter = 'f'; Code = "fvljfff" |}
  {| Min = 12; Max = 15; Letter = 'w'; Code = "wwwwwrwwwwwwwwvwwww" |}
  {| Min = 2; Max = 4; Letter = 'g'; Code = "gggmg" |}
  {| Min = 1; Max = 2; Letter = 'w'; Code = "wwxwqw" |}
  {| Min = 11; Max = 18; Letter = 's'; Code = "sssssssssscqsssssn" |}
  {| Min = 12; Max = 15; Letter = 'r'; Code = "rrcrrrrrrrwlbgrh" |}
  {| Min = 9; Max = 14; Letter = 't'; Code = "ttttwsttrnttthtt" |}
  {| Min = 4; Max = 5; Letter = 'n'; Code = "nnnnnnnn" |}
  {| Min = 15; Max = 16; Letter = 'w'; Code = "wwwwwwwwwtwwwdwww" |}
  {| Min = 7; Max = 12; Letter = 'g'; Code = "qfgjwcggglgggwmlhr" |}
  {| Min = 1; Max = 15; Letter = 'z'; Code = "zzsphzzzvzzzbpzzz" |}
  {| Min = 14; Max = 16; Letter = 'l'; Code = "llllllllxlllljlsll" |}
  {| Min = 3; Max = 4; Letter = 'x'; Code = "xxxx" |}
  {| Min = 3; Max = 6; Letter = 'w'; Code = "dhwpjw" |}
  {| Min = 2; Max = 7; Letter = 'v'; Code = "zvvkxcvbtwx" |}
  {| Min = 2; Max = 5; Letter = 'x'; Code = "whpfx" |}
  {| Min = 4; Max = 6; Letter = 'f'; Code = "mfndfc" |}
  {| Min = 5; Max = 7; Letter = 'z'; Code = "tznzzzn" |}
  {| Min = 3; Max = 5; Letter = 'l'; Code = "jtllld" |}
  {| Min = 15; Max = 17; Letter = 'd'; Code = "jbdrdnlqdbdlvzwhbdz" |}
  {| Min = 14; Max = 18; Letter = 'd'; Code = "ddddddddddddddddddd" |}
  {| Min = 3; Max = 4; Letter = 'c'; Code = "vlvsqxcmjsk" |}
  {| Min = 10; Max = 14; Letter = 'b'; Code = "bpbhbbdvblbsfbbrdb" |}
  {| Min = 6; Max = 7; Letter = 'g'; Code = "dgmchcbmhhxcbvg" |}
  {| Min = 11; Max = 15; Letter = 'd'; Code = "ddddddddddndddqddddd" |}
  {| Min = 3; Max = 11; Letter = 'g'; Code = "ggxlggggggfgg" |}
  {| Min = 3; Max = 5; Letter = 'g'; Code = "gcrgw" |}
  {| Min = 4; Max = 8; Letter = 'q'; Code = "xqlqrqqkk" |}
  {| Min = 3; Max = 4; Letter = 'x'; Code = "zrqndxxxf" |}
  {| Min = 4; Max = 9; Letter = 'l'; Code = "llllllllcllglll" |}
  {| Min = 4; Max = 6; Letter = 'd'; Code = "bdddddztdbd" |}
  {| Min = 7; Max = 9; Letter = 's'; Code = "zkghrssxm" |}
  {| Min = 4; Max = 6; Letter = 'x'; Code = "xgncxfx" |}
  {| Min = 8; Max = 9; Letter = 'c'; Code = "cccccccwn" |}
  {| Min = 9; Max = 10; Letter = 'm'; Code = "mmmzmmmmmmhvm" |}
  {| Min = 4; Max = 5; Letter = 'c'; Code = "cvhcc" |}
  {| Min = 2; Max = 5; Letter = 'k'; Code = "kfkqgxqfk" |}
  {| Min = 16; Max = 18; Letter = 's'; Code = "ssssssssssksssssss" |}
  {| Min = 4; Max = 5; Letter = 'k'; Code = "zbknk" |}
  {| Min = 3; Max = 4; Letter = 'h'; Code = "hjdhcfsv" |}
  {| Min = 4; Max = 6; Letter = 'f'; Code = "lfrfdfhfqf" |}
  {| Min = 2; Max = 11; Letter = 'k'; Code = "kkkkkkktkkkkkk" |}
  {| Min = 1; Max = 9; Letter = 'f'; Code = "fkwtffhffxftdfz" |}
  {| Min = 8; Max = 15; Letter = 'b'; Code = "bbbbprztvbbbkbbbbbb" |}
  {| Min = 6; Max = 10; Letter = 's'; Code = "ssssfwssswgk" |}
  {| Min = 11; Max = 12; Letter = 't'; Code = "trcthtmljttv" |}
  {| Min = 3; Max = 4; Letter = 's'; Code = "svss" |}
  {| Min = 6; Max = 8; Letter = 'p'; Code = "ptpppzpldvcdbbbpwmjg" |}
  {| Min = 11; Max = 17; Letter = 'x'; Code = "cxpqbxxxxbxxxqxxn" |}
  {| Min = 11; Max = 14; Letter = 'z'; Code = "pzzzzwpxnzzkzzz" |}
  {| Min = 6; Max = 7; Letter = 'c'; Code = "ccccccc" |}
  {| Min = 1; Max = 2; Letter = 'z'; Code = "grzzz" |}
  {| Min = 8; Max = 10; Letter = 'd'; Code = "xgmswdsvtb" |}
  {| Min = 7; Max = 8; Letter = 'c'; Code = "kcccccdp" |}
  {| Min = 12; Max = 13; Letter = 'f'; Code = "btcnxsclqznxmf" |}
  {| Min = 4; Max = 11; Letter = 'k'; Code = "grhkjkkkkkkkkpksktkk" |}
  {| Min = 15; Max = 16; Letter = 'z'; Code = "zzzzzzzzszzzzzzz" |}
  {| Min = 8; Max = 11; Letter = 'v'; Code = "vvvvvvvgvvlvvvvv" |}
  {| Min = 1; Max = 2; Letter = 'c'; Code = "qqccc" |}
  {| Min = 2; Max = 4; Letter = 'w'; Code = "nvkgzdfw" |}
  {| Min = 3; Max = 12; Letter = 'f'; Code = "bfvpftfffwdfff" |}
  {| Min = 5; Max = 6; Letter = 'h'; Code = "wghnhtvzhhz" |}
  {| Min = 4; Max = 6; Letter = 'v'; Code = "vpvmvp" |}
  {| Min = 5; Max = 9; Letter = 'z'; Code = "nfgwzzzszz" |}
  {| Min = 10; Max = 11; Letter = 'b'; Code = "bbbxbbbbbbbb" |}
  {| Min = 6; Max = 7; Letter = 'g'; Code = "ggnggzw" |}
  {| Min = 2; Max = 6; Letter = 'c'; Code = "bcrccc" |}
  {| Min = 1; Max = 13; Letter = 's'; Code = "dsssssssssssls" |}
  {| Min = 1; Max = 6; Letter = 'j'; Code = "fjjjjcj" |}
  {| Min = 4; Max = 14; Letter = 'p'; Code = "pzvfnpfppblfjngpkzj" |}
  {| Min = 1; Max = 2; Letter = 'p'; Code = "pppv" |}
  {| Min = 4; Max = 5; Letter = 't'; Code = "gttsktt" |}
  {| Min = 3; Max = 13; Letter = 'w'; Code = "wwwrbwwwwwcwwwrwxg" |}
  {| Min = 12; Max = 14; Letter = 'r'; Code = "zrtrdrrrjrhrmrl" |}
  {| Min = 5; Max = 6; Letter = 'b'; Code = "bnbbbwbbw" |}
  {| Min = 13; Max = 19; Letter = 'g'; Code = "ggqbhgfggfpgqgggggx" |}
  {| Min = 11; Max = 12; Letter = 'b'; Code = "bbbbbkbbbbnp" |}
  {| Min = 10; Max = 11; Letter = 'c'; Code = "hcvccchqshj" |}
  {| Min = 6; Max = 8; Letter = 'k'; Code = "krvlcfkrxx" |}
  {| Min = 5; Max = 13; Letter = 'd'; Code = "dddddddddddddd" |}
  {| Min = 5; Max = 7; Letter = 'w'; Code = "wwwzbwkhvwwm" |}
  {| Min = 6; Max = 10; Letter = 'z'; Code = "zzzzznzzzrzz" |}
  {| Min = 11; Max = 12; Letter = 'h'; Code = "hhhhhhhthfcr" |}
  {| Min = 9; Max = 13; Letter = 't'; Code = "ttttsxtttkgtttgtt" |}
  {| Min = 11; Max = 13; Letter = 'r'; Code = "nrrrrrrrrrprtrrrrrrr" |}
  {| Min = 16; Max = 17; Letter = 'l'; Code = "kllllhlllllllllzdl" |}
  {| Min = 4; Max = 6; Letter = 'w'; Code = "wwjwvw" |}
  {| Min = 1; Max = 3; Letter = 'j'; Code = "mjnxbqvzfjgjsjr" |}
  {| Min = 7; Max = 8; Letter = 't'; Code = "pltpspvt" |}
  {| Min = 5; Max = 13; Letter = 'm'; Code = "lmzmmnqfmmjmtm" |}
  {| Min = 1; Max = 15; Letter = 'd'; Code = "djxhfqjwjmdndhg" |}
  {| Min = 4; Max = 6; Letter = 'r'; Code = "hkrrrrgsdsx" |}
  {| Min = 1; Max = 7; Letter = 'r'; Code = "srrrrrrrsprh" |}
  {| Min = 3; Max = 6; Letter = 'g'; Code = "dbgtqwkwkgzqxbgbgkh" |}
  {| Min = 15; Max = 18; Letter = 's'; Code = "sssslrsspssssszssp" |}
  {| Min = 8; Max = 11; Letter = 'q'; Code = "qqvkqpdqdqqz" |}
  {| Min = 1; Max = 3; Letter = 'c'; Code = "cccscccc" |}
  {| Min = 5; Max = 9; Letter = 'd'; Code = "wpfzlqnsdrtlvwnd" |}
  {| Min = 7; Max = 9; Letter = 'f'; Code = "qrdblxfnf" |}
  {| Min = 3; Max = 4; Letter = 'z'; Code = "flzz" |}
  {| Min = 11; Max = 12; Letter = 'c'; Code = "ccccccccccpwc" |}
  {| Min = 3; Max = 4; Letter = 'v'; Code = "ltjwvcv" |}
  {| Min = 13; Max = 15; Letter = 'p'; Code = "ppppppppppppfpp" |}
  {| Min = 14; Max = 15; Letter = 'r'; Code = "zrrrrrrrbrrrrrkrr" |}
  {| Min = 2; Max = 5; Letter = 'n'; Code = "lnwnnsmfd" |}
  {| Min = 4; Max = 7; Letter = 't'; Code = "ttctrtt" |}
  {| Min = 5; Max = 6; Letter = 'w'; Code = "hsfpwcwrfwxmwww" |}
  {| Min = 5; Max = 8; Letter = 'b'; Code = "bbbbmbbfbb" |}
  {| Min = 1; Max = 3; Letter = 'z'; Code = "czzp" |}
  {| Min = 4; Max = 6; Letter = 'h'; Code = "hhbhhh" |}
  {| Min = 16; Max = 18; Letter = 'j'; Code = "jjjjjjjjjjjjjjjjjq" |}
  {| Min = 1; Max = 2; Letter = 'n'; Code = "zdlwqzlnnp" |}
  {| Min = 5; Max = 16; Letter = 'm'; Code = "mmmmxmmmmmmmmmmjm" |}
  {| Min = 3; Max = 5; Letter = 'h'; Code = "hhlfhghhhjh" |}
  {| Min = 2; Max = 6; Letter = 'f'; Code = "vkfbpf" |}
  {| Min = 5; Max = 6; Letter = 'j'; Code = "jjjjjjj" |}
  {| Min = 4; Max = 8; Letter = 'q'; Code = "qdmzqlln" |}
  {| Min = 6; Max = 7; Letter = 'x'; Code = "xpxxxjtxs" |}
  {| Min = 2; Max = 5; Letter = 'z'; Code = "znzzxq" |}
  {| Min = 8; Max = 13; Letter = 'j'; Code = "jjjjwvvjcjjjkj" |}
  {| Min = 2; Max = 7; Letter = 'x'; Code = "xkxwxxncxtxvxxlxr" |}
  {| Min = 4; Max = 13; Letter = 'm'; Code = "zrxmqfmmjgcgqwk" |}
  {| Min = 2; Max = 4; Letter = 'b'; Code = "bqbbbb" |}
  {| Min = 2; Max = 3; Letter = 'j'; Code = "gjjlv" |}
  {| Min = 14; Max = 17; Letter = 'n'; Code = "nnnqnnntnnnnndnnmnnn" |}
  {| Min = 3; Max = 8; Letter = 'c'; Code = "tlcmcccx" |}
  {| Min = 2; Max = 7; Letter = 'c'; Code = "ccmlbscmb" |}
  {| Min = 7; Max = 8; Letter = 'l'; Code = "ljflbgll" |}
  {| Min = 2; Max = 11; Letter = 'p'; Code = "dqkzvmptdgchclbw" |}
  {| Min = 7; Max = 12; Letter = 'w'; Code = "wwwwwwwwwwww" |}
  {| Min = 1; Max = 10; Letter = 'r'; Code = "htpmgskvrzr" |}
  {| Min = 1; Max = 4; Letter = 'm'; Code = "fndmmmmztmcgmx" |}
  {| Min = 3; Max = 4; Letter = 't'; Code = "qmtttzqtt" |}
  {| Min = 11; Max = 17; Letter = 'g'; Code = "zggggdgdglqfsgqxggg" |}
  {| Min = 2; Max = 10; Letter = 'c'; Code = "ccccfkvxcc" |}
  {| Min = 13; Max = 15; Letter = 'g'; Code = "ggggggggggggnggzgg" |}
  {| Min = 4; Max = 14; Letter = 'z'; Code = "zzzzzzzzzlzzzzzzzz" |}
  {| Min = 4; Max = 13; Letter = 'g'; Code = "ggglggggggggqg" |}
  {| Min = 12; Max = 13; Letter = 'x'; Code = "xzxxxxxxxxxkxx" |}
  {| Min = 3; Max = 7; Letter = 's'; Code = "sssssssjss" |}
  {| Min = 9; Max = 11; Letter = 'j'; Code = "jjtjrjzjjhjjkbjjjbjt" |}
  {| Min = 4; Max = 6; Letter = 'r'; Code = "rkrfrrrrr" |}
  {| Min = 5; Max = 6; Letter = 'q'; Code = "qmqcgqqq" |}
  {| Min = 4; Max = 17; Letter = 't'; Code = "tttmtttcttttttttttt" |}
  {| Min = 2; Max = 4; Letter = 'd'; Code = "fsbdddpdd" |}
  {| Min = 11; Max = 15; Letter = 'b'; Code = "xbbbbbbbbbbbrbqpbb" |}
  {| Min = 4; Max = 6; Letter = 's'; Code = "lkqsqwkszzsjst" |}
  {| Min = 13; Max = 14; Letter = 'l'; Code = "lllllllllllllllllll" |}
  {| Min = 12; Max = 15; Letter = 't'; Code = "btlttmbthtttttdtt" |}
  {| Min = 9; Max = 12; Letter = 'q'; Code = "mkcqrnfqxqnqskpq" |}
  {| Min = 3; Max = 5; Letter = 'm'; Code = "stmmmgqjfv" |}
  {| Min = 5; Max = 11; Letter = 'v'; Code = "vvlgzvvvvvv" |}
  {| Min = 2; Max = 6; Letter = 'n'; Code = "znntrnhnntbpjkgnqv" |}
  {| Min = 7; Max = 8; Letter = 'd'; Code = "sgmddfddjrtv" |}
  {| Min = 6; Max = 10; Letter = 'k'; Code = "kqkkbnkkpdk" |}
  {| Min = 5; Max = 7; Letter = 'n'; Code = "nnnznnngnl" |}
  {| Min = 9; Max = 16; Letter = 'q'; Code = "qqqqqqqqjqqqqqqbqqqq" |}
  {| Min = 2; Max = 4; Letter = 'w'; Code = "bwww" |}
  {| Min = 9; Max = 11; Letter = 'c'; Code = "jfpvdqftgqx" |}
  {| Min = 5; Max = 11; Letter = 'c'; Code = "ccccckcccfccccc" |}
  {| Min = 1; Max = 2; Letter = 'c'; Code = "ccbsvl" |}
  {| Min = 1; Max = 5; Letter = 'd'; Code = "ddmmd" |}
  {| Min = 2; Max = 8; Letter = 'j'; Code = "ntjhkjjmjcj" |}
  {| Min = 5; Max = 6; Letter = 'p'; Code = "ppppskpkpp" |}
  {| Min = 4; Max = 8; Letter = 't'; Code = "ztptgptzmtttw" |}
  {| Min = 5; Max = 6; Letter = 'k'; Code = "gvjzkmdkfmxnlq" |}
  {| Min = 17; Max = 18; Letter = 'f'; Code = "ffffffffffffffffdf" |}
  {| Min = 1; Max = 13; Letter = 's'; Code = "sssbhztsnssgs" |}
  {| Min = 3; Max = 6; Letter = 'v'; Code = "mlvvvfvwxvvxv" |}
  {| Min = 6; Max = 11; Letter = 'p'; Code = "npkcbslzpvtkjp" |}
  {| Min = 2; Max = 4; Letter = 'm'; Code = "gbsjxmjxcdsdnv" |}
  {| Min = 16; Max = 17; Letter = 'b'; Code = "bcbbbbbbbbbfbbbbvbbb" |}
  {| Min = 17; Max = 18; Letter = 'h'; Code = "lmshsjxbbhhrqhfqchkh" |}
  {| Min = 1; Max = 3; Letter = 'l'; Code = "llllk" |}
  {| Min = 5; Max = 8; Letter = 'h'; Code = "dhhwhhhnhh" |}
  {| Min = 9; Max = 12; Letter = 'f'; Code = "ffdhpzffkffpfcffjf" |}
  {| Min = 1; Max = 5; Letter = 'k'; Code = "khbfkkc" |}
  {| Min = 1; Max = 8; Letter = 'p'; Code = "ndkpxvpgpppp" |}
  {| Min = 1; Max = 7; Letter = 't'; Code = "tljjkttqptttvt" |}
  {| Min = 16; Max = 17; Letter = 't'; Code = "tttttttttrttttttt" |}
  {| Min = 13; Max = 18; Letter = 'z'; Code = "ztzzzzgzzzzglzzndjzf" |}
  {| Min = 13; Max = 15; Letter = 'q'; Code = "qqqqqqqqqqqqqqqqq" |}
  {| Min = 6; Max = 8; Letter = 'v'; Code = "vvvvvvvv" |}
  {| Min = 10; Max = 15; Letter = 'q'; Code = "fqcxlxvhvgfzxwvqv" |}
  {| Min = 4; Max = 12; Letter = 'g'; Code = "btdgdglbprjg" |}
  {| Min = 3; Max = 5; Letter = 't'; Code = "gttjt" |}
  {| Min = 1; Max = 11; Letter = 'w'; Code = "twwwwwwwwwnwww" |}
  {| Min = 2; Max = 3; Letter = 'f'; Code = "jgbfcfbfftccffff" |}
  {| Min = 1; Max = 2; Letter = 'r'; Code = "rrrnwr" |}
  {| Min = 11; Max = 16; Letter = 'r'; Code = "rrrrrrrrrrrrrrrr" |}
  {| Min = 1; Max = 16; Letter = 'q'; Code = "qqqqqqqqqqqqqqqqqqqq" |}
  {| Min = 7; Max = 16; Letter = 'z'; Code = "zwzzzzfzzzzzzzzz" |}
  {| Min = 10; Max = 11; Letter = 'f'; Code = "fflfmfrjfhjffff" |}
  {| Min = 1; Max = 5; Letter = 't'; Code = "npxgd" |}
  {| Min = 7; Max = 8; Letter = 'n'; Code = "nknnnngbxd" |}
  {| Min = 4; Max = 6; Letter = 'k'; Code = "kkkkkkk" |}
  {| Min = 5; Max = 19; Letter = 'd'; Code = "xtdddjxfvxgddddndndq" |}
  {| Min = 8; Max = 12; Letter = 's'; Code = "vstssxssssss" |}
  {| Min = 3; Max = 6; Letter = 'f'; Code = "tlfftfxqhbltbrg" |}
  {| Min = 17; Max = 19; Letter = 'd'; Code = "ddddddddddddddddtdc" |}
  {| Min = 2; Max = 9; Letter = 'q'; Code = "qqqqnqgbq" |}
  {| Min = 8; Max = 14; Letter = 'k'; Code = "wknbkkkbkzkgkdkk" |}
  {| Min = 17; Max = 18; Letter = 'n'; Code = "nnnntnnvnnnnnnnnnnnn" |}
  {| Min = 15; Max = 16; Letter = 'p'; Code = "ppppppppppppppppp" |}
  {| Min = 2; Max = 4; Letter = 'h'; Code = "hwhhhh" |}
  {| Min = 4; Max = 9; Letter = 'd'; Code = "ddddddddddd" |}
  {| Min = 1; Max = 8; Letter = 's'; Code = "sssssssrs" |}
  {| Min = 14; Max = 15; Letter = 'z'; Code = "zfzzzzzzzcfzzzz" |}
  {| Min = 5; Max = 6; Letter = 'k'; Code = "kkkkkkk" |}
  {| Min = 5; Max = 6; Letter = 'x'; Code = "xxxxxvx" |}
  {| Min = 18; Max = 19; Letter = 'r'; Code = "rrrrjrkbttrjpfjqftm" |}
  {| Min = 11; Max = 12; Letter = 'f'; Code = "fffffffffsff" |}
  {| Min = 11; Max = 17; Letter = 'z'; Code = "hwzdfvbpbxzfpjwmzq" |}
  {| Min = 1; Max = 11; Letter = 'm'; Code = "mxkmnxfbtnmvmtzdqjl" |}
  {| Min = 3; Max = 4; Letter = 'd'; Code = "ddjg" |}
  {| Min = 17; Max = 18; Letter = 'b'; Code = "jnlntbblbbqbkqmbbb" |} |]